/**
 * rich-text.js
 * Handles formatting for content generated by the Admin Quill Editor.
 * Automatically injects necessary CSS styles for lists, headers, etc.
 */

// 1. Inject Typography CSS automatically
// This restores standard styling (bullets, bold, headings) that Tailwind resets.
const style = document.createElement('style');
style.textContent = `
    .rich-text-content {
        font-family: 'Inter', sans-serif;
        color: #334155; /* slate-700 */
        font-size: 0.95rem;
        line-height: 1.6;
    }
    .rich-text-content p { margin-bottom: 1em; }
    .rich-text-content h1 { font-size: 1.5rem; font-weight: 700; color: #0f172a; margin-top: 1.5em; margin-bottom: 0.75em; }
    .rich-text-content h2 { font-size: 1.25rem; font-weight: 600; color: #1e293b; margin-top: 1.25em; margin-bottom: 0.5em; }
    .rich-text-content strong, .rich-text-content b { font-weight: 600; color: #0f172a; }
    .rich-text-content em, .rich-text-content i { font-style: italic; }
    .rich-text-content u { text-decoration: underline; text-decoration-color: #cbd5e1; text-underline-offset: 2px; }
    
    /* Lists */
    .rich-text-content ul { list-style-type: disc; padding-left: 1.5rem; margin-bottom: 1em; }
    .rich-text-content ol { list-style-type: decimal; padding-left: 1.5rem; margin-bottom: 1em; }
    .rich-text-content li { margin-bottom: 0.25em; padding-left: 0.25em; }
    
    /* Links */
    .rich-text-content a { color: var(--color-brand, #0284c7); text-decoration: none; font-weight: 500; }
    .rich-text-content a:hover { text-decoration: underline; }
    
    /* Blockquotes */
    .rich-text-content blockquote { border-left: 4px solid #cbd5e1; padding-left: 1rem; margin-left: 0; font-style: italic; color: #64748b; }

    /* Quill specific alignments */
    .ql-align-center { text-align: center; }
    .ql-align-right { text-align: right; }
    .ql-align-justify { text-align: justify; }
`;
document.head.appendChild(style);

/**
 * Strips HTML tags to create a plain text preview for Cards/Summaries.
 * e.g. "<p><strong>Hello</strong></p>" -> "Hello"
 */
export function stripHtml(html) {
    if (!html) return "";
    const tmp = document.createElement("DIV");
    tmp.innerHTML = html;
    return tmp.textContent || tmp.innerText || "";
}

/**
 * Returns the HTML string wrapped in the specific class required to apply styles.
 * Use this for Detail views.
 */
export function formatRichText(html) {
    if (!html) return "";
    return `<div class="rich-text-content">${html}</div>`;
}